### ISSUE TITLE
我使用make命令构建hello_world例子时，被告知缺少规则无法构建的错误

### ISSUE THREAD

**Issue by Typedefining** [d0u9/Linux-Device-Driver-Rust#1]
make[2]: *** 没有规则可制作目标“/XXX/Linux-Device-Driver-Rust-master/eg_01_hello_world/main.o”，由“/XXX/Linux-Device-Driver-Rust-master/eg_01_hello_world/hello_world.o” 需求。(XXX为/home/用户名)

**Comment by d0u9** [comment]
Have your properly build the kernel with:

```
LIBCLANG_PATH=/path/to/libclang make -j LLVM=1 bzImage
LIBCLANG_PATH=/path/to/libclang make -j LLVM=1 modules
```

The second command generates the necessary files essential to build a kernel module.

**Comment by Typedefining** [comment]
> Have your properly build the kernel with:
> 
> ```
> LIBCLANG_PATH=/path/to/libclang make -j LLVM=1 bzImage
> LIBCLANG_PATH=/path/to/libclang make -j LLVM=1 modules
> ```
> 
> The second command generates the necessary files essential to build a kernel module.

Thanks for you reply. 
I'm new at this. Now I‘m trying to build linux-5.11.5 on my Ubuntu ,which uses linux-5.8.0-59-generic.
But when I input : LIBCLANG_PATH=/usr/lib/clang make -j LLVM=1 bzImage , I got this error: Compiler lacks asm-goto support.
And Here is my development environment:

gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

So, can you tell me what should I do to solve it or where can I find  docs?
Thank you very much.

**Comment by d0u9** [comment]
Currently, Rust for Linux is still a standalone project and is not merged back to mainline. If you want a try of brand new features of Rust support, use https://github.com/Rust-for-Linux/linux instead.

The `linux-5.11.5` doesn't contain the Rust part yet, and the `hello world` example will absolutely fail when compiled against it.

**Comment by Typedefining** [comment]
yes,I will build rust-for-linux now.
thank you
