### ISSUE TITLE
error: optimization level needs to be between 0-3, s or z (instead was ``)

### ISSUE THREAD

**Issue by ZechariahZheng** [d0u9/Linux-Device-Driver-Rust#3]
I follow your step to make hello_world module, but it appears: 

```shell
make -C /home/zzs/Documents/linux-rust M=/home/zzs/Documents/my_mod LLVM=1 modules
make[1]: Entering directory '/home/zzs/Documents/linux-rust'
  RUSTC [M] /home/zzs/Documents/my_mod/rust_test.o
error: optimization level needs to be between 0-3, s or z (instead was ``)

make[2]: *** [scripts/Makefile.build:346: /home/zzs/Documents/my_mod/rust_test.o] Error 1
make[1]: *** [Makefile:1975: /home/zzs/Documents/my_mod] Error 2
make[1]: Leaving directory '/home/zzs/Documents/linux-rust'
make: *** [Makefile:3: all] Error 2
```

maybe need to set optimization level in Makefile. But I'm a newer for it , how to set set optimization level in Makefile.

**Comment by d0u9** [comment]
I can't reproduce this. What is the version of the kernel you are compiling against? And, check your rust version to make sure it is the 1.57.0

**Comment by ZechariahZheng** [comment]
@d0u9
Environment:

- Ubuntu 20.04.3 LTS
- bindgen v0.56.0
- rustup 1.24.3 (ce5817a94 2021-05-31)
  - info: The currently active `rustc` version is `rustc 1.57.0 (f1edd0429 2021-11-29)`
- clang version 13.0.0 (https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz)
- Kernel version 5.16.0-rc6

**Comment by d0u9** [comment]
Does your rust kernel compiled by rustc 1.57.0?

**Comment by ZechariahZheng** [comment]
@d0u9 Thanks for your replying. I have solved it. I found it in Kernel hacking → Rust hacking → Optimization level. 
Then enable it, it runs success!

**Comment by d0u9** [comment]
https://github.com/Rust-for-Linux/linux/issues/605
